import type { Metadata } from 'next';
import './globals.css';

import { Navbar } from '../components/ui/Navbar';
import { getSessionUser } from '../lib/session';

export const metadata: Metadata = {
    title: {
        default: 'Create Nextjs App',
        template: '%s | My Website',
    },
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const { userName, userImage } = await getSessionUser();

    return (
        <html lang="en">
            <body className="min-h-screen w-full">
                <nav className="fixed left-0 top-0 h-screen w-65 bg-white">
                    <Navbar userName={userName} userImage={userImage} />
                </nav>
                <main className="ml-65 min-h-screen">{children}</main>
            </body>
        </html>
    );
}
