import type { Metadata } from 'next';

import './globals.css';

// import { WorkspaceStateSync } from '../components/shared/WorkspaceStateSync';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '../components/shared/AppSidebar';
import { SidebarController } from '../components/shared/SidebarControll';
import { auth } from '../lib/auth';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: {
        default: 'Create Nextjs App',
        template: '%s | My Website',
    },
    description: 'Generated by create next app',
};

const session = await auth();
const user = session?.user;


export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={cn('font-sans', geist.variable)}>
            <body className="min-h-screen w-full">
                <SidebarProvider>
                    <SidebarController />
                    <AppSidebar user={user} />
                    <main className="w-full h-screen">{children}</main>
                </SidebarProvider>
            </body>
        </html>
    );
}
